version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    labels:
      - "kind/dependencies"
      - "bot"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    versioning-strategy: "increase"
    allow:
      - dependency-type: "production"
    labels:
      - "kind/dependencies"
      - "bot"
